title: Ruby on rails
author: T-Deepthy
email: deeps1929@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on rails is a server baased web applicatin written on ruby. 
  Rails is a model-view-controller framework providing default structure 
  for a database, a web services, a web pages.
# social links
twitter_username: deeps1929@gmail.com
github_username:  T-Deepthy

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal

